# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_new_test',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/nbdev_new_test',
                'lib_path': 'nbdev_new_test'},
  'syms': {'nbdev_new_test.core': {'nbdev_new_test.core.foo': ('core.html#foo', 'nbdev_new_test/core.py')}}}
